# Generated by Django 3.0.8 on 2020-07-24 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_site', '0002_auto_20200723_1746'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='image',
            new_name='illustration_image',
        ),
        migrations.RemoveField(
            model_name='article',
            name='file',
        ),
    ]
