# Generated by Django 3.0.8 on 2020-07-24 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_site', '0003_auto_20200724_0827'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='illustration_image',
        ),
    ]
