# Generated by Django 3.0.8 on 2020-08-16 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_site', '0005_about'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='tags',
        ),
        migrations.AddField(
            model_name='article',
            name='illustration',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='article',
            name='content_category',
            field=models.CharField(choices=[('python', 'python'), ('javaScript', 'javaScript'), ('html', 'html'), ('css', 'css'), ('Unclassified', 'Unclassified')], default='Unclassified', max_length=25),
        ),
    ]
