# Generated by Django 3.0.8 on 2020-08-17 05:20

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_site', '0006_auto_20200816_1322'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='illustration',
            field=models.ImageField(blank=True, null=True, upload_to='uploads'),
        ),
    ]
