# Generated by Django 3.0.8 on 2020-08-20 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_site', '0008_auto_20200818_1043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='illustration',
            field=models.ImageField(blank=True, default='article.png', null=True, upload_to='illustrations'),
        ),
    ]
