# Generated by Django 3.0.8 on 2020-08-23 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_site', '0008_auto_20200818_1043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='content_category',
            field=models.CharField(choices=[('python', 'python'), ('javaScript', 'javaScript'), ('html', 'html'), ('css', 'css')], default='Unclassified', max_length=25),
        ),
        migrations.AlterField(
            model_name='article',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
